### PR TITLE
Add browserify transform to support transpiling

### PR DESCRIPTION
**Pull request by MarkReeder**

### CODE REVIEW

**Comment by 75lb** [comment]
naturally, i'm reluctant to bake arbitrary metadata relating to arbitrary third party packages into this package. Besides, the config you're asking me to add might not suit everyone. 

Do you need to support old versions of node, is that why you need it?

**Comment by MarkReeder** [comment]
Totally understand that sentiment and appreciate your desire to keep arbitrary content out of your codebase. In this case, the metadata instructs browserify to transform the contents of the module, since by default it leaves things in `node_modules` alone. In my particular case, part of my build toolchain (uglify) fails when attempting to deal with the ES2015 let/const statements. Adding this to the `package.json` also allows transpilation to ES5, which is still necessary to support ~20% of global internet users: http://caniuse.com/#feat=let - I can work around this issue, but the most typical approach I've seen with js modules is to write in ES6 and have a prepublish step that transpiles to ES5. This is an alternative solution to that approach, which allows published ES6 code to be dealt with by ES5 tooling and for ES5 build targets. If you'd prefer to go down the prepublish route, I'd be open to updating this diff to use that approach.

**Comment by 75lb** [comment]
ok, you need to support old versions of node.. no problem, I updated version 1 to include your changes - see version 1.1.2 and the branch [here](https://github.com/75lb/sort-array/tree/v1).

Version 2 will remain node 4 and above. Thanks again for the input.

**Comment by MarkReeder** [comment]
works for me- thanks!

**Pull request closed without merging**
